### ISSUE TITLE
Enable docker hub github connection

### ISSUE THREAD

**Issue by williamdes** [xhprof/docker-xh-tool#1]
@mailoman could you please connect GitHub with docker hub and link this repository to the docker image?

**Comment by mailoman** [comment]
I think yes )

**Comment by mailoman** [comment]
isn't it already linked?

**Comment by williamdes** [comment]
You are right, it is in fact there seems to have a trick that does not display th ui tabs when not the owner but the link still does work

https://hub.docker.com/r/xhprof/xh-tool/dockerfile

![Screenshot_20210129_163844_com brave browser](https://user-images.githubusercontent.com/7784660/106295734-16d71700-6251-11eb-9e77-effbdc5ec4a5.jpg)
